### ISSUE TITLE
Couldn't Add Settings thru Rails_admin

### ISSUE THREAD

**Issue by zekedran** [rs-pro/rails_admin_settings#13]
I couldn't add any settings through admin_panel, though I could do from console

![image](https://user-images.githubusercontent.com/8567893/28557146-642c5e7a-7128-11e7-9534-8089df24dfcb.png)

![image](https://user-images.githubusercontent.com/8567893/28557182-8bf48b9e-7128-11e7-9488-bee94f5a2847.png)

**Comment by zekedran** [comment]
Note that the field `Key` doesn't appear at all in edit and the only editable field is `Value`

**Comment by glebtv** [comment]
Settings currently cannot be created via rails admin
This is by design.
They are saved to database with default value when you use them for the first time in your code.
