### ISSUE TITLE
undefined method `new' for "fog":String

### ISSUE THREAD

**Issue by duchaiweb** [rs-pro/rails_admin_settings#7]
I used gem 'fog', 'fog-aws', 'carrierwave'
And put gem 'rails_admin_settings' after all

![download](https://cloud.githubusercontent.com/assets/7385055/11173900/009dca70-8c4f-11e5-8051-5169ca94b242.png)

**Comment by glebtv** [comment]
I think it's unrelated to this gem, probably it's something wrong with carrierwave\fog config
